services:
  - type: web
    name: ai-job-screening-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    # Run both worker and web server in same instance for cost efficiency (Note: Not recommended for high load)
    startCommand: "chmod +x start.sh && ./start.sh"
    plan: free
    envVars:
      - key: REDIS_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: COHERE_API_KEY
        sync: false
