repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        files: Backend_old/.*\.py
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: Backend_old/.*\.py
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v6.0.0
    hooks:
      - id: isort
        files: Backend_old/.*\.py
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.3.3']
        files: frontend/.*\.(ts|tsx|css|json)
